// Physics Theories and Models Data
const physicsData = {
  "name": "Physics as known today",
  "year": 2026,
  "children": [
    {
      "name": "Classical Mechanics",
      "year": 1687,
      "children": [
        {
          "name": "Newtonian Mechanics",
          "year": 1687,
          "children": [
            {"name": "Newton's Laws of Motion", "year": 1687, "summary": "Three fundamental laws describing the relationship between motion and forces.", "people": ["Isaac Newton"], "tags": [{"name": "force", "explanation": "These laws describe how forces cause changes in motion and the relationship between force, mass, and acceleration."}], "papers": [{"title": "Philosophiæ Naturalis Principia Mathematica", "link": "https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica"}]},
            {"name": "Universal Gravitation", "year": 1687, "summary": "Every particle attracts every other particle with a force proportional to their masses.", "people": ["Isaac Newton"], "tags": [{"name": "force", "explanation": "Describes the gravitational force that acts between all masses in the universe."}]},
            {"name": "Conservation of Momentum", "year": 1644, "summary": "Total momentum of a closed system remains constant in the absence of external forces.", "people": ["René Descartes"]},
            {"name": "Conservation of Energy", "year": 1847, "summary": "Energy cannot be created or destroyed, only transformed from one form to another.", "people": ["Julius Robert von Mayer", "James Prescott Joule"]},
            {"name": "Noether's Theorem", "year": 1918, "summary": "Fundamental theorem connecting symmetries to conservation laws. States that every differentiable symmetry of the action of a physical system corresponds to a conservation law. For example, time translation symmetry implies conservation of energy, and spatial translation symmetry implies conservation of momentum.", "people": ["Emmy Noether"], "papers": [{"title": "Invariante Variationsprobleme", "link": "https://en.wikipedia.org/wiki/Noether%27s_theorem"}]}
          ]
        },
        {
          "name": "Analytical Mechanics",
          "year": 1788,
          "children": [
            {"name": "Lagrangian Formulation", "year": 1788, "summary": "Mechanics reformulated using kinetic and potential energy in a single function.", "people": ["Joseph-Louis Lagrange"]},
            {"name": "Hamiltonian Formulation", "year": 1834, "summary": "Mechanics expressed in terms of position and momentum coordinates.", "people": ["William Rowan Hamilton"]},
            {"name": "Action Principle", "year": 1744, "summary": "Physical systems follow paths that minimize or maximize the action integral.", "people": ["Pierre Louis Maupertuis"]},
            {"name": "Canonical Transformations", "year": 1834, "summary": "Coordinate transformations that preserve the form of Hamilton's equations.", "people": ["William Rowan Hamilton"]}
          ]
        },
        {
          "name": "Continuum Mechanics",
          "year": 1822,
          "children": [
            {"name": "Fluid Dynamics", "year": 1755, "summary": "Study of fluids in motion and the forces acting on them.", "people": ["Leonhard Euler", "Daniel Bernoulli"]},
            {"name": "Elasticity Theory", "year": 1822, "summary": "Behavior of materials that return to original shape after deformation.", "people": ["Claude-Louis Navier", "Augustin-Louis Cauchy"]},
            {"name": "Wave Propagation", "year": 1747, "summary": "How waves travel through different media and interact with boundaries.", "people": ["Jean le Rond d'Alembert"]},
            {"name": "Navier-Stokes Equations", "year": 1822, "summary": "Fundamental equations describing the motion of viscous fluid substances.", "people": ["Claude-Louis Navier", "George Gabriel Stokes"]}
          ]
        }
      ]
    },
    {
      "name": "Quantum Physics",
      "year": 1900,
      "children": [
        {
          "name": "Quantum Mechanics",
          "year": 1925,
          "children": [
            {"name": "Schrödinger Equation", "year": 1926, "summary": "Fundamental equation describing how quantum states evolve over time.", "people": ["Erwin Schrödinger"], "tags": [{"name": "time", "explanation": "The equation describes the time evolution of quantum states, showing how wave functions change over time."}], "papers": [{"title": "An Undulatory Theory of the Mechanics of Atoms and Molecules", "link": "https://journals.aps.org/pr/abstract/10.1103/PhysRev.28.1049"}], "nobel": 1933},
            {"name": "Heisenberg Uncertainty Principle", "year": 1927, "summary": "Fundamental limit to precision of simultaneous measurement of complementary properties.", "people": ["Werner Heisenberg"], "papers": [{"title": "Über den anschaulichen Inhalt der quantentheoretischen Kinematik und Mechanik", "link": "https://en.wikipedia.org/wiki/Uncertainty_principle"}], "nobel": 1932},
            {"name": "Wave-Particle Duality", "year": 1924, "summary": "Concept that all matter exhibits both wave and particle properties.", "people": ["Louis de Broglie"], "nobel": 1929},
            {"name": "Quantum Entanglement", "year": 1935, "summary": "Phenomenon where particles become correlated and share quantum states.", "people": ["Albert Einstein", "Boris Podolsky", "Nathan Rosen"]}
          ]
        },
        {
          "name": "Quantum Field Theory",
          "year": 1927,
          "children": [
            {"name": "Standard Model", "year": 1975, "summary": "Theory describing three of the four fundamental forces and all known elementary particles.", "people": ["Sheldon Glashow", "Abdus Salam", "Steven Weinberg"], "tags": [{"name": "force", "explanation": "The Standard Model describes three of the four fundamental forces: electromagnetic, weak nuclear, and strong nuclear forces."}], "nobel": 1979},
            {"name": "Quantum Electrodynamics", "year": 1948, "summary": "Quantum field theory of electromagnetism describing interactions of light and matter.", "people": ["Richard Feynman", "Julian Schwinger", "Sin-Itiro Tomonaga"], "tags": [{"name": "force", "explanation": "Describes the electromagnetic force at the quantum level, governing interactions between charged particles and photons."}], "nobel": 1965},
            {"name": "Quantum Chromodynamics", "year": 1973, "summary": "Theory of the strong nuclear force that binds quarks and gluons.", "people": ["Murray Gell-Mann", "Harald Fritzsch", "Heinrich Leutwyler"], "tags": [{"name": "force", "explanation": "Describes the strong nuclear force that binds quarks together to form protons, neutrons, and other hadrons."}], "nobel": 1969},
            {"name": "Electroweak Theory", "year": 1967, "summary": "Unified description of electromagnetic and weak nuclear forces.", "people": ["Sheldon Glashow", "Abdus Salam", "Steven Weinberg", "Gerardus 't Hooft", "Martinus J. G. Veltman"], "tags": [{"name": "force", "explanation": "Unifies the electromagnetic and weak nuclear forces into a single theoretical framework."}], "nobel": 1979}
          ]
        },
        {
          "name": "Information Theory",
          "year": 1948,
          "children": [
            {"name": "Shannon Entropy", "year": 1948, "summary": "Mathematical measure of uncertainty or information content in a message or system. Fundamental concept in information theory that quantifies the amount of information needed to describe a random variable.", "people": ["Claude Shannon"], "kyoto": 1985},
            {"name": "Channel Capacity", "year": 1948, "summary": "Maximum rate at which information can be reliably transmitted over a communication channel, as determined by Shannon's channel coding theorem.", "people": ["Claude Shannon"]}
          ]
        },
        {
          "name": "Quantum Information",
          "year": 1980,
          "children": [
            {"name": "Quantum Computing", "year": 1982, "summary": "Computing paradigm that uses quantum mechanical phenomena like superposition and entanglement to perform computations.", "people": ["Richard Feynman", "Paul Benioff", "Yuri Manin"]},
            {"name": "Quantum Cryptography", "year": 1984, "summary": "Cryptographic protocols that use quantum mechanical properties to secure communication.", "people": ["Charles Bennett", "Gilles Brassard"]},
            {"name": "Bell's Theorem", "year": 1964, "summary": "Theorem proving that no local hidden variable theory can reproduce all predictions of quantum mechanics.", "people": ["John Stewart Bell"], "nobel": 2022},
            {"name": "Superdeterminism", "year": 1985, "summary": "Interpretation of quantum mechanics suggesting that apparent randomness is actually deterministic, with initial conditions of the universe correlated in a way that makes quantum measurements appear random. Proposed as a way to explain quantum correlations without violating locality.", "people": ["John Stewart Bell"]},
            {"name": "Quantum Teleportation", "year": 1993, "summary": "Process of transferring quantum information from one location to another using entanglement.", "people": ["Charles Bennett", "Gilles Brassard", "Claude Crépeau", "Richard Jozsa", "Asher Peres", "William Wootters"], "nobel": 2022}
          ]
        }
      ]
    },
    {
      "name": "Relativity",
      "year": 1905,
      "children": [
        {
          "name": "Special Relativity",
          "year": 1905,
          "children": [
            {"name": "Lorentz Transformations", "year": 1904, "summary": "Mathematical transformations that relate space and time coordinates between different inertial reference frames.", "people": ["Hendrik Lorentz"], "tags": [{"name": "time", "explanation": "These transformations show how time coordinates change when moving between different reference frames in special relativity."}], "nobel": 1902},
            {"name": "Time Dilation", "year": 1905, "summary": "Phenomenon where time passes slower for objects moving relative to an observer.", "people": ["Albert Einstein"], "tags": [{"name": "time", "explanation": "Directly describes how time itself is affected by relative motion, with time passing slower for moving objects."}], "papers": [{"title": "On the Electrodynamics of Moving Bodies", "link": "https://en.wikipedia.org/wiki/Annus_Mirabilis_papers"}], "nobel": 1921},
            {"name": "Length Contraction", "year": 1905, "summary": "Phenomenon where the length of an object appears shorter when moving relative to an observer.", "people": ["Albert Einstein"]},
            {"name": "Mass-Energy Equivalence", "year": 1905, "summary": "Principle that mass and energy are equivalent and can be converted into each other, expressed as E=mc².", "people": ["Albert Einstein"], "papers": [{"title": "Does the Inertia of a Body Depend Upon Its Energy Content?", "link": "https://en.wikipedia.org/wiki/Annus_Mirabilis_papers"}]}
          ]
        },
        {
          "name": "General Relativity",
          "year": 1915,
          "children": [
            {"name": "Einstein Field Equations", "year": 1915, "summary": "Set of equations describing how matter and energy curve spacetime.", "people": ["Albert Einstein"], "tags": [{"name": "force", "explanation": "These equations describe gravity as a force resulting from the curvature of spacetime caused by matter and energy."}], "papers": [{"title": "The Field Equations of Gravitation", "link": "https://en.wikipedia.org/wiki/Einstein_field_equations"}]},
            {"name": "Black Holes", "year": 1916, "summary": "Regions of spacetime where gravity is so strong that nothing can escape.", "people": ["Karl Schwarzschild", "Albert Einstein"], "nobel": 2020},
            {"name": "Holographic Principle", "year": 1993, "summary": "Principle suggesting that the description of a volume of space can be encoded on a lower-dimensional boundary. Inspired by black hole thermodynamics, it proposes that all information within a region can be represented as a hologram on its boundary.", "people": ["Gerardus 't Hooft", "Leonard Susskind"]},
            {"name": "Loop Quantum Gravity", "year": 1988, "summary": "Theory attempting to merge quantum mechanics with general relativity by quantizing spacetime itself. Proposes that space is composed of discrete loops and networks, providing a background-independent approach to quantum gravity.", "people": ["Carlo Rovelli", "Lee Smolin", "Abhay Ashtekar"]},
            {"name": "Gravitational Waves", "year": 1916, "summary": "Ripples in spacetime caused by accelerating massive objects.", "people": ["Albert Einstein"], "nobel": 2017},
            {"name": "Cosmological Models", "year": 1917, "summary": "Theoretical frameworks describing the large-scale structure and evolution of the universe.", "people": ["Albert Einstein", "Willem de Sitter", "Alexander Friedmann"], "tags": [{"name": "time", "explanation": "These models describe how the universe evolves over cosmological time scales, from the Big Bang to the present and future."}]}
          ]
        },
        {
          "name": "Relativistic Mechanics",
          "year": 1905,
          "children": [
            {"name": "Relativistic Kinematics", "year": 1905, "summary": "Study of motion in the absence of forces, accounting for relativistic effects.", "people": ["Albert Einstein"]},
            {"name": "Relativistic Dynamics", "year": 1905, "summary": "Study of motion under the influence of forces, incorporating relativistic corrections.", "people": ["Albert Einstein"]},
            {"name": "Minkowski Spacetime", "year": 1908, "summary": "Four-dimensional mathematical model combining three-dimensional space with time into a single continuum.", "people": ["Hermann Minkowski"], "tags": [{"name": "time", "explanation": "Unifies space and time into a four-dimensional spacetime continuum, where time is treated as a dimension on equal footing with spatial dimensions."}]},
            {"name": "Twin Paradox", "year": 1911, "summary": "Thought experiment demonstrating time dilation where a traveling twin ages slower than a stationary twin.", "people": ["Albert Einstein", "Paul Langevin"], "tags": [{"name": "time", "explanation": "Demonstrates the real-world consequences of time dilation, showing how time passes differently for observers in relative motion."}]}
          ]
        }
      ]
    },
    {
      "name": "Thermodynamics",
      "year": 1850,
      "children": [
        {
          "name": "Classical Thermodynamics",
          "year": 1850,
          "children": [
            {"name": "Laws of Thermodynamics", "year": 1850, "summary": "Four fundamental laws governing energy, entropy, and temperature in thermodynamic systems.", "people": ["Rudolf Clausius", "William Thomson"], "tags": [{"name": "time", "explanation": "The second law establishes the arrow of time by stating that entropy increases over time, giving time its directionality."}, {"name": "exergy", "explanation": "The laws of thermodynamics, particularly the second law, are fundamental to understanding exergy, which measures the maximum useful work obtainable from a system."}]},
            {"name": "Entropy", "year": 1865, "summary": "Measure of disorder or randomness in a system, central to the second law of thermodynamics.", "people": ["Rudolf Clausius"], "tags": [{"name": "time", "explanation": "Entropy's increase over time defines the arrow of time, explaining why processes are irreversible and why we remember the past but not the future."}, {"name": "exergy", "explanation": "Entropy is directly related to exergy destruction - the greater the entropy generation, the more exergy is destroyed in a process."}]},
            {"name": "Heat Engines", "year": 1824, "summary": "Devices that convert thermal energy into mechanical work through cyclic processes.", "people": ["Sadi Carnot"], "tags": [{"name": "exergy", "explanation": "Heat engines convert exergy (available energy) into useful work, with efficiency limited by exergy destruction due to irreversibilities."}]},
            {"name": "Carnot Cycle", "year": 1824, "summary": "Theoretical reversible thermodynamic cycle that defines the maximum possible efficiency for a heat engine.", "people": ["Sadi Carnot"], "tags": [{"name": "exergy", "explanation": "The Carnot cycle represents the ideal case where all exergy is converted to work with no exergy destruction, achieving maximum exergy efficiency."}]},
            {"name": "Exergy", "year": 1956, "summary": "Maximum useful work obtainable from a system as it reaches equilibrium with its environment. Also known as available energy or availability.", "people": ["Zoran Rant"], "tags": [{"name": "exergy", "explanation": "Exergy is the measure of the maximum useful work that can be extracted from a system, measuring energy quality and potential for conversion to work."}]}
          ]
        },
        {
          "name": "Statistical Mechanics",
          "year": 1871,
          "children": [
            {"name": "Boltzmann Distribution", "year": 1871, "summary": "Probability distribution describing the statistical behavior of particles in thermal equilibrium.", "people": ["Ludwig Boltzmann"]},
            {"name": "Fermi-Dirac Statistics", "year": 1926, "summary": "Statistical distribution describing particles with half-integer spin that obey the Pauli exclusion principle.", "people": ["Enrico Fermi", "Paul Dirac"]},
            {"name": "Bose-Einstein Statistics", "year": 1924, "summary": "Statistical distribution describing particles with integer spin that can occupy the same quantum state.", "people": ["Satyendra Nath Bose", "Albert Einstein"]},
            {"name": "Partition Function", "year": 1902, "summary": "Mathematical function that encodes the statistical properties of a thermodynamic system in equilibrium.", "people": ["Josiah Willard Gibbs"]}
          ]
        },
        {
          "name": "Non-Equilibrium Thermodynamics",
          "year": 1931,
          "children": [
            {"name": "Onsager reciprocal relations", "year": 1931, "summary": "Symmetry relations between transport coefficients in systems near thermodynamic equilibrium.", "people": ["Lars Onsager"], "tags": [{"name": "exergy", "explanation": "Onsager relations describe irreversible processes that lead to exergy destruction in non-equilibrium systems."}]},
            {"name": "Fluctuation-Dissipation Theorem", "year": 1951, "summary": "Theorem connecting the response of a system to external perturbations with its internal fluctuations.", "people": ["Herbert Callen", "Theodore Welton"], "tags": [{"name": "exergy", "explanation": "Fluctuations and dissipation processes are directly related to exergy destruction in thermodynamic systems."}]},
            {"name": "Brownian Motion", "year": 1905, "summary": "Random motion of particles suspended in a fluid resulting from collisions with surrounding molecules.", "people": ["Albert Einstein", "Marian Smoluchowski"]},
            {"name": "Diffusion Processes", "year": 1905, "summary": "Process by which particles spread from regions of high concentration to regions of low concentration.", "people": ["Albert Einstein", "Adolf Fick"], "tags": [{"name": "exergy", "explanation": "Diffusion processes involve exergy destruction as concentration gradients are dissipated, reducing the system's capacity to do work."}]}
          ]
        }
      ]
    },
    {
      "name": "Electromagnetism",
      "year": 1865,
      "children": [
        {
          "name": "Classical Electrodynamics",
          "year": 1865,
          "children": [
            {"name": "Maxwell's Equations", "year": 1865, "summary": "Four fundamental equations describing electricity, magnetism, and their relationship.", "people": ["James Clerk Maxwell"], "papers": [{"title": "A Dynamical Theory of the Electromagnetic Field", "link": "https://en.wikipedia.org/wiki/A_Dynamical_Theory_of_the_Electromagnetic_Field"}]},
            {"name": "Electromagnetic Waves", "year": 1865, "summary": "Oscillating electric and magnetic fields that propagate through space.", "people": ["James Clerk Maxwell", "Heinrich Hertz"]},
            {"name": "Lorentz Force", "year": 1895, "summary": "Force experienced by a charged particle moving through electric and magnetic fields.", "people": ["Hendrik Lorentz"], "tags": [{"name": "force", "explanation": "Describes the electromagnetic force acting on charged particles moving through electric and magnetic fields."}]},
            {"name": "Gauss's Law", "year": 1835, "summary": "Relationship between electric flux through a closed surface and enclosed charge.", "people": ["Carl Friedrich Gauss"]}
          ]
        },
        {
          "name": "Optics",
          "year": 1801,
          "children": [
            {"name": "Wave Optics", "year": 1801, "summary": "Branch of optics that treats light as a wave, explaining phenomena like interference and diffraction.", "people": ["Thomas Young"]},
            {"name": "Geometric Optics", "year": 1637, "summary": "Branch of optics that treats light as rays, describing reflection and refraction using geometric principles.", "people": ["René Descartes"]},
            {"name": "Interference", "year": 1801, "summary": "Phenomenon where two or more waves superpose to form a resultant wave of greater or lower amplitude.", "people": ["Thomas Young"]},
            {"name": "Diffraction", "year": 1665, "summary": "Bending and spreading of waves around obstacles or through apertures, characteristic of wave behavior.", "people": ["Francesco Maria Grimaldi", "Christiaan Huygens"]}
          ]
        },
        {
          "name": "Plasma Physics",
          "year": 1928,
          "children": [
            {"name": "Magnetohydrodynamics", "year": 1942, "summary": "Study of the dynamics of electrically conducting fluids in magnetic fields.", "people": ["Hannes Alfvén"]},
            {"name": "Plasma Waves", "year": 1928, "summary": "Oscillations and waves that propagate through plasma, a state of matter with free charged particles.", "people": ["Irving Langmuir", "Lewi Tonks"]},
            {"name": "Fusion Theory", "year": 1950, "summary": "Theoretical framework describing nuclear fusion, the process of combining light atomic nuclei to form heavier ones.", "people": ["Lyman Spitzer"]},
            {"name": "Solar Wind Models", "year": 1958, "summary": "Theoretical models describing the continuous stream of charged particles emitted from the Sun's corona.", "people": ["Eugene Parker"]}
          ]
        }
      ]
    },
    {
      "name": "Particle Physics",
      "year": 1930,
      "children": [
        {
          "name": "Elementary Particles",
          "year": 1932,
          "children": [
            {"name": "Quarks", "year": 1964, "summary": "Elementary particles that combine to form composite particles like protons and neutrons.", "people": ["Murray Gell-Mann", "George Zweig"], "nobel": 1969},
            {"name": "Leptons", "year": 1947, "summary": "Class of elementary particles that do not participate in strong interactions, including electrons and neutrinos.", "people": ["Cecil Powell"], "nobel": 1950},
            {"name": "Gauge Bosons", "year": 1983, "people": ["Carlo Rubbia", "Simon van der Meer"], "tags": [{"name": "force", "explanation": "These particles are the force carriers that mediate the fundamental forces: photons (electromagnetic), W and Z bosons (weak), and gluons (strong)."}], "nobel": 1984},
            {"name": "Higgs Boson", "year": 2012, "summary": "Elementary particle that gives mass to other particles through the Higgs field.", "people": ["Peter Higgs", "François Englert"], "nobel": 2013}
          ]
        },
        {
          "name": "Symmetries",
          "year": 1918,
          "children": [
            {"name": "Gauge Symmetry", "year": 1918, "summary": "Symmetry principle underlying the fundamental forces, describing invariance under local transformations.", "people": ["Hermann Weyl"]},
            {"name": "Gauge Fixing", "year": 1950, "summary": "Procedure in gauge theories to remove redundant degrees of freedom by choosing a specific gauge condition. Essential for quantizing gauge fields and making calculations well-defined. Common gauges include Lorenz gauge, Coulomb gauge, and axial gauge.", "people": ["Julian Schwinger", "Richard Feynman", "Sin-Itiro Tomonaga"]},
            {"name": "CP Violation", "year": 1964, "summary": "Violation of the combined symmetry of charge conjugation and parity, explaining matter-antimatter asymmetry.", "people": ["James Cronin", "Val Fitch"]},
            {"name": "Supersymmetry", "year": 1971, "summary": "Theoretical symmetry relating fermions and bosons, proposing a partner particle for each known particle.", "people": ["Yuri Golfand", "Evgeny Likhtman"]},
            {"name": "String Theory", "year": 1970, "summary": "Theoretical framework proposing that fundamental particles are one-dimensional vibrating strings rather than point particles.", "people": ["Yoichiro Nambu", "Holger Bech Nielsen", "Leonard Susskind"]}
          ]
        },
        {
          "name": "Accelerator Physics",
          "year": 1930,
          "children": [
            {"name": "Collider Experiments", "year": 1956, "summary": "Experiments using particle accelerators to collide particles at high energies to study fundamental physics.", "people": ["Donald Kerst"]},
            {"name": "Particle Detectors", "year": 1911, "summary": "Instruments designed to detect and measure properties of subatomic particles and radiation.", "people": ["Hans Geiger", "Ernest Rutherford"]},
            {"name": "Beam Dynamics", "year": 1950, "summary": "Study of the motion and control of charged particle beams in accelerators and storage rings.", "people": ["Ernest Courant", "Milton Livingston", "Hartland Snyder"]},
            {"name": "Synchrotron Radiation", "year": 1947, "summary": "Electromagnetic radiation emitted when charged particles are accelerated in curved paths, typically in synchrotrons.", "people": ["Elder", "Gurewitsch", "Langmuir"]}
          ]
        }
      ]
    }
  ]
};

// Nobel Prize in Physics awards by year
const nobelPrizes = {
  1901: "Wilhelm Conrad Röntgen - Discovery of X-rays",
  1902: "Hendrik Lorentz and Pieter Zeeman - Influence of magnetism upon radiation phenomena",
  1903: "Antoine Henri Becquerel, Pierre Curie, and Marie Curie - Discovery of spontaneous radioactivity",
  1904: "Lord Rayleigh - Density of gases and discovery of argon",
  1905: "Philipp Lenard - Work on cathode rays",
  1906: "Joseph John Thomson - Conduction of electricity by gases",
  1907: "Albert A. Michelson - Optical precision instruments and spectroscopic and metrological investigations",
  1908: "Gabriel Lippmann - Method of reproducing colours photographically based on the phenomenon of interference",
  1909: "Guglielmo Marconi and Karl Ferdinand Braun - Development of wireless telegraphy",
  1910: "Johannes Diderik van der Waals - Equation of state for gases and liquids",
  1911: "Wilhelm Wien - Laws governing the radiation of heat",
  1912: "Nils Gustaf Dalén - Automatic regulators for use in conjunction with gas accumulators for illuminating lighthouses and buoys",
  1913: "Heike Kamerlingh Onnes - Properties of matter at low temperatures, production of liquid helium",
  1914: "Max von Laue - Diffraction of X-rays by crystals",
  1915: "William Henry Bragg and William Lawrence Bragg - Analysis of crystal structure by means of X-rays",
  1916: "No prize awarded",
  1917: "Charles Glover Barkla - Discovery of the characteristic Röntgen radiation of the elements",
  1918: "Max Planck - Discovery of energy quanta",
  1919: "Johannes Stark - Discovery of the Doppler effect in canal rays and the splitting of spectral lines in electric fields",
  1920: "Charles Édouard Guillaume - Precision measurements in physics by his discovery of anomalies in nickel steel alloys",
  1921: "Albert Einstein - Photoelectric effect",
  1922: "Niels Bohr - Structure of atoms and radiation emanating from them",
  1923: "Robert Andrews Millikan - Work on the elementary charge of electricity and on the photoelectric effect",
  1924: "Manne Siegbahn - Discoveries and research in the field of X-ray spectroscopy",
  1925: "James Franck and Gustav Hertz - Laws governing the impact of an electron upon an atom",
  1926: "Jean Baptiste Perrin - Work on the discontinuous structure of matter, and especially for his discovery of sedimentation equilibrium",
  1927: "Arthur Holly Compton - Discovery of the effect named after him; Charles Thomson Rees Wilson - Method of making the paths of electrically charged particles visible by condensation of vapour",
  1928: "Owen Willans Richardson - Work on the thermionic phenomenon and especially for the discovery of the law named after him",
  1929: "Louis de Broglie - Discovery of the wave nature of electrons",
  1930: "Chandrasekhara Venkata Raman - Work on the scattering of light and for the discovery of the effect named after him",
  1931: "No prize awarded",
  1932: "Werner Heisenberg - Creation of quantum mechanics",
  1933: "Erwin Schrödinger and Paul Dirac - Discovery of new productive forms of atomic theory",
  1934: "No prize awarded",
  1935: "James Chadwick - Discovery of the neutron",
  1936: "Victor Franz Hess - Discovery of cosmic radiation; Carl David Anderson - Discovery of the positron",
  1937: "Clinton Joseph Davisson and George Paget Thomson - Experimental discovery of the diffraction of electrons by crystals",
  1938: "Enrico Fermi - Demonstrations of the existence of new radioactive elements produced by neutron irradiation, and for his related discovery of nuclear reactions brought about by slow neutrons",
  1939: "Ernest Lawrence - Invention and development of the cyclotron and for results obtained with it, especially with regard to artificial radioactive elements",
  1940: "No prize awarded",
  1941: "No prize awarded",
  1942: "No prize awarded",
  1943: "Otto Stern - Contribution to the development of the molecular ray method and his discovery of the magnetic moment of the proton",
  1944: "Isidor Isaac Rabi - Resonance method for recording the magnetic properties of atomic nuclei",
  1945: "Wolfgang Pauli - Discovery of the Exclusion Principle",
  1946: "Percy Williams Bridgman - Invention of an apparatus to produce extremely high pressures, and for the discoveries he made therewith in the field of high pressure physics",
  1947: "Edward Victor Appleton - Investigations of the physics of the upper atmosphere especially for the discovery of the so-called Appleton layer",
  1948: "Patrick Maynard Stuart Blackett - Development of the Wilson cloud chamber method, and his discoveries therewith in the fields of nuclear physics and cosmic radiation",
  1949: "Hideki Yukawa - Prediction of the existence of mesons on the basis of theoretical work on nuclear forces",
  1950: "Cecil Frank Powell - Development of the photographic method of studying nuclear processes and his discoveries regarding mesons made with this method",
  1951: "John Douglas Cockcroft and Ernest Thomas Sinton Walton - Pioneer work on the transmutation of atomic nuclei by artificially accelerated atomic particles",
  1952: "Felix Bloch and Edward Mills Purcell - Development of new methods for nuclear magnetic precision measurements and discoveries in connection therewith",
  1953: "Frits Zernike - Demonstration of the phase contrast method, especially for his invention of the phase contrast microscope",
  1954: "Max Born - Fundamental research in quantum mechanics, especially for his statistical interpretation of the wavefunction; Walther Bothe - Coincidence method and his discoveries made therewith",
  1955: "Willis Eugene Lamb - Discoveries concerning the fine structure of the hydrogen spectrum; Polykarp Kusch - Precision determination of the magnetic moment of the electron",
  1956: "John Bardeen, Walter Houser Brattain, and William Shockley - Research on semiconductors and their discovery of the transistor effect",
  1957: "Tsung-Dao Lee and Chen-Ning Yang - Discovery of violations of the principle of parity conservation",
  1958: "Pavel Alekseyevich Cherenkov, Il'ja Mikhailovich Frank, and Igor Yevgenyevich Tamm - Discovery and the interpretation of the Cherenkov effect",
  1959: "Emilio Gino Segrè and Owen Chamberlain - Discovery of the antiproton",
  1960: "Donald Arthur Glaser - Invention of the bubble chamber",
  1961: "Robert Hofstadter - Pioneering studies of electron scattering in atomic nuclei and for his thereby achieved discoveries concerning the structure of the nucleons; Rudolf Ludwig Mössbauer - Research concerning the resonance absorption of gamma radiation and his discovery in this connection of the effect which bears his name",
  1962: "Lev Davidovich Landau - Pioneering theories for condensed matter, especially liquid helium",
  1963: "Eugene Paul Wigner - Contributions to the theory of the atomic nucleus and the elementary particles, particularly through the discovery and application of fundamental symmetry principles; Maria Goeppert-Mayer and J. Hans D. Jensen - Discoveries concerning nuclear shell structure",
  1964: "Charles Hard Townes, Nikolay Gennadiyevich Basov, and Aleksandr Mikhailovich Prokhorov - Fundamental work in the field of quantum electronics, which has led to the construction of oscillators and amplifiers based on the maser-laser principle",
  1965: "Sin-Itiro Tomonaga, Julian Schwinger, and Richard P. Feynman - Fundamental work in quantum electrodynamics, with deep-ploughing consequences for the physics of elementary particles",
  1966: "Alfred Kastler - Discovery and development of optical methods for studying Hertzian resonances in atoms",
  1967: "Hans Albrecht Bethe - Contributions to the theory of nuclear reactions, especially his discoveries concerning the energy production in stars",
  1968: "Luis Walter Alvarez - Decisive contributions to elementary particle physics, in particular the discovery of a large number of resonance states, made possible through his development of the technique of using hydrogen bubble chamber and data analysis",
  1969: "Murray Gell-Mann - Contributions and discoveries concerning the classification of elementary particles and their interactions",
  1970: "Hannes Alfvén - Fundamental work and discoveries in magnetohydrodynamics with fruitful applications in different parts of plasma physics; Louis Néel - Fundamental work and discoveries concerning antiferromagnetism and ferrimagnetism which have led to important applications in solid state physics",
  1971: "Dennis Gabor - Invention and development of the holographic method",
  1972: "John Bardeen, Leon Neil Cooper, and John Robert Schrieffer - Jointly developed theory of superconductivity",
  1973: "Leo Esaki and Ivar Giaever - Experimental discoveries regarding tunneling phenomena in semiconductors and superconductors respectively; Brian David Josephson - Theoretical predictions of the properties of a supercurrent through a tunnel barrier",
  1974: "Martin Ryle and Antony Hewish - Pioneering research in radio astrophysics",
  1975: "Aage Niels Bohr, Ben Roy Mottelson, and Leo James Rainwater - Discovery of the connection between collective motion and particle motion in atomic nuclei and the development of the theory of the structure of the atomic nucleus based on this connection",
  1976: "Burton Richter and Samuel Chao Chung Ting - Pioneering work in the discovery of a heavy elementary particle of a new kind",
  1977: "Philip Warren Anderson, Nevill Francis Mott, and John Hasbrouck Van Vleck - Fundamental theoretical investigations of the electronic structure of magnetic and disordered systems",
  1978: "Pyotr Leonidovich Kapitsa - Basic inventions and discoveries in the area of low-temperature physics; Arno Allan Penzias and Robert Woodrow Wilson - Discovery of cosmic microwave background radiation",
  1979: "Sheldon Lee Glashow, Abdus Salam, and Steven Weinberg - Contributions to the theory of the unified weak and electromagnetic interaction between elementary particles",
  1980: "James Watson Cronin and Val Logsdon Fitch - Discovery of violations of fundamental symmetry principles in the decay of neutral K-mesons",
  1981: "Nicolaas Bloembergen and Arthur Leonard Schawlow - Development of laser spectroscopy; Kai Manne Börje Siegbahn - Contribution to the development of high-resolution electron spectroscopy",
  1982: "Kenneth G. Wilson - Theory for critical phenomena in connection with phase transitions",
  1983: "Subrahmanyan Chandrasekhar - Theoretical studies of the physical processes of importance to the structure and evolution of the stars; William Alfred Fowler - Theoretical and experimental studies of the nuclear reactions of importance in the formation of the chemical elements in the universe",
  1984: "Carlo Rubbia and Simon van der Meer - Decisive contributions to the large project, which led to the discovery of the field particles W and Z, communicators of weak interaction",
  1985: "Klaus von Klitzing - Discovery of the quantized Hall effect",
  1986: "Ernst Ruska - Fundamental work in electron optics, and for the design of the first electron microscope; Gerd Binnig and Heinrich Rohrer - Design of the scanning tunneling microscope",
  1987: "J. Georg Bednorz and K. Alexander Müller - Important breakthrough in the discovery of superconductivity in ceramic materials",
  1988: "Leon M. Lederman, Melvin Schwartz, and Jack Steinberger - Neutrino beam method and the demonstration of the doublet structure of the leptons through the discovery of the muon neutrino",
  1989: "Norman F. Ramsey - Invention of the separated oscillatory fields method and its use in the hydrogen maser and other atomic clocks; Hans G. Dehmelt and Wolfgang Paul - Development of the ion trap technique",
  1990: "Jerome I. Friedman, Henry W. Kendall, and Richard E. Taylor - Pioneering investigations concerning deep inelastic scattering of electrons on protons and bound neutrons",
  1991: "Pierre-Gilles de Gennes - Discovering that methods developed for studying order phenomena in simple systems can be generalized to more complex forms of matter",
  1992: "Georges Charpak - Invention and development of particle detectors, in particular the multiwire proportional chamber",
  1993: "Russell A. Hulse and Joseph H. Taylor Jr. - Discovery of a new type of pulsar, a discovery that has opened up new possibilities for the study of gravitation",
  1994: "Bertram N. Brockhouse - Development of neutron spectroscopy; Clifford G. Shull - Development of the neutron diffraction technique",
  1995: "Martin L. Perl - Discovery of the tau lepton; Frederick Reines - Detection of the neutrino",
  1996: "David M. Lee, Douglas D. Osheroff, and Robert C. Richardson - Discovery of superfluidity in helium-3",
  1997: "Steven Chu, Claude Cohen-Tannoudji, and William D. Phillips - Development of methods to cool and trap atoms with laser light",
  1998: "Robert B. Laughlin, Horst L. Störmer, and Daniel C. Tsui - Discovery of a new form of quantum fluid with fractionally charged excitations",
  1999: "Gerardus 't Hooft and Martinus J. G. Veltman - Elucidating the quantum structure of electroweak interactions in physics",
  2000: "Zhores I. Alferov and Herbert Kroemer - Developing semiconductor heterostructures used in high-speed- and opto-electronics; Jack S. Kilby - Part in the invention of the integrated circuit",
  2001: "Eric A. Cornell, Wolfgang Ketterle, and Carl E. Wieman - Achievement of Bose-Einstein condensation in dilute gases of alkali atoms, and for early fundamental studies of the properties of the condensates",
  2002: "Raymond Davis Jr. and Masatoshi Koshiba - Pioneering contributions to astrophysics, in particular for the detection of cosmic neutrinos; Riccardo Giacconi - Pioneering contributions to astrophysics, which have led to the discovery of cosmic X-ray sources",
  2003: "Alexei A. Abrikosov, Vitaly L. Ginzburg, and Anthony J. Leggett - Pioneering contributions to the theory of superconductors and superfluids",
  2004: "David J. Gross, H. David Politzer, and Frank Wilczek - Discovery of asymptotic freedom in the theory of the strong interaction",
  2005: "Roy J. Glauber - Contribution to the quantum theory of optical coherence; John L. Hall and Theodor W. Hänsch - Contributions to the development of laser-based precision spectroscopy",
  2006: "John C. Mather and George F. Smoot - Discovery of the blackbody form and anisotropy of the cosmic microwave background radiation",
  2007: "Albert Fert and Peter Grünberg - Discovery of giant magnetoresistance",
  2008: "Makoto Kobayashi and Toshihide Maskawa - Discovery of the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature; Yoichiro Nambu - Discovery of the mechanism of spontaneous broken symmetry in subatomic physics",
  2009: "Charles K. Kao - Groundbreaking achievements concerning the transmission of light in fibers for optical communication; Willard S. Boyle and George E. Smith - Invention of an imaging semiconductor circuit – the CCD sensor",
  2010: "Andre Geim and Konstantin Novoselov - Groundbreaking experiments regarding the two-dimensional material graphene",
  2011: "Saul Perlmutter, Brian P. Schmidt, and Adam G. Riess - Discovery of the accelerating expansion of the Universe through observations of distant supernovae",
  2012: "Serge Haroche and David J. Wineland - Ground-breaking experimental methods that enable measuring and manipulation of individual quantum systems",
  2013: "François Englert and Peter W. Higgs - Theoretical discovery of a mechanism that contributes to our understanding of the origin of mass of subatomic particles",
  2014: "Isamu Akasaki, Hiroshi Amano, and Shuji Nakamura - Invention of efficient blue light-emitting diodes which has enabled bright and energy-saving white light sources",
  2015: "Takaaki Kajita and Arthur B. McDonald - Discovery of neutrino oscillations, which shows that neutrinos have mass",
  2016: "David J. Thouless, F. Duncan M. Haldane, and J. Michael Kosterlitz - Theoretical discoveries of topological phase transitions and topological phases of matter",
  2017: "Rainer Weiss, Barry C. Barish, and Kip S. Thorne - Decisive contributions to the LIGO detector and the observation of gravitational waves",
  2018: "Arthur Ashkin - Optical tweezers and their application to biological systems; Gérard Mourou and Donna Strickland - Method of generating high-intensity, ultra-short optical pulses",
  2019: "James Peebles - Theoretical discoveries in physical cosmology; Michel Mayor and Didier Queloz - Discovery of an exoplanet orbiting a solar-type star",
  2020: "Roger Penrose - Discovery that black hole formation is a robust prediction of the general theory of relativity; Reinhard Genzel and Andrea Ghez - Discovery of a supermassive compact object at the centre of our galaxy",
  2021: "Syukuro Manabe and Klaus Hasselmann - Physical modelling of Earth's climate, quantifying variability and reliably predicting global warming; Giorgio Parisi - Discovery of the interplay of disorder and fluctuations in physical systems from atomic to planetary scales",
  2022: "Alain Aspect, John F. Clauser, and Anton Zeilinger - Experiments with entangled photons, establishing the violation of Bell inequalities and pioneering quantum information science",
  2023: "Pierre Agostini, Ferenc Krausz, and Anne L'Huillier - Experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter",
  2024: "John F. Clauser, Alain Aspect, and Anton Zeilinger - For experiments with entangled photons, establishing the violation of Bell inequalities and pioneering quantum information science"
};

// Nobel Prize years for people (array of years they won)
const peopleNobel = {
  "Wilhelm Conrad Röntgen": [1901],
  "Hendrik Lorentz": [1902],
  "Pieter Zeeman": [1902],
  "Antoine Henri Becquerel": [1903],
  "Pierre Curie": [1903],
  "Marie Curie": [1903],
  "Lord Rayleigh": [1904],
  "Philipp Lenard": [1905],
  "Joseph John Thomson": [1906],
  "Albert A. Michelson": [1907],
  "Gabriel Lippmann": [1908],
  "Guglielmo Marconi": [1909],
  "Karl Ferdinand Braun": [1909],
  "Johannes Diderik van der Waals": [1910],
  "Wilhelm Wien": [1911],
  "Nils Gustaf Dalén": [1912],
  "Heike Kamerlingh Onnes": [1913],
  "Max von Laue": [1914],
  "William Henry Bragg": [1915],
  "William Lawrence Bragg": [1915],
  "Charles Glover Barkla": [1917],
  "Max Planck": [1918],
  "Johannes Stark": [1919],
  "Charles Édouard Guillaume": [1920],
  "Albert Einstein": [1921],
  "Niels Bohr": [1922],
  "Robert Andrews Millikan": [1923],
  "Manne Siegbahn": [1924],
  "James Franck": [1925],
  "Gustav Hertz": [1925],
  "Jean Baptiste Perrin": [1926],
  "Arthur Holly Compton": [1927],
  "Charles Thomson Rees Wilson": [1927],
  "Owen Willans Richardson": [1928],
  "Louis de Broglie": [1929],
  "Chandrasekhara Venkata Raman": [1930],
  "Werner Heisenberg": [1932],
  "Erwin Schrödinger": [1933],
  "Paul Dirac": [1933],
  "James Chadwick": [1935],
  "Victor Franz Hess": [1936],
  "Carl David Anderson": [1936],
  "Clinton Joseph Davisson": [1937],
  "George Paget Thomson": [1937],
  "Enrico Fermi": [1938],
  "Ernest Lawrence": [1939],
  "Otto Stern": [1943],
  "Isidor Isaac Rabi": [1944],
  "Wolfgang Pauli": [1945],
  "Percy Williams Bridgman": [1946],
  "Edward Victor Appleton": [1947],
  "Patrick Maynard Stuart Blackett": [1948],
  "Hideki Yukawa": [1949],
  "Cecil Powell": [1950],
  "John Douglas Cockcroft": [1951],
  "Ernest Thomas Sinton Walton": [1951],
  "Felix Bloch": [1952],
  "Edward Mills Purcell": [1952],
  "Frits Zernike": [1953],
  "Max Born": [1954],
  "Walther Bothe": [1954],
  "Willis Eugene Lamb": [1955],
  "Polykarp Kusch": [1955],
  "John Bardeen": [1956, 1972],
  "Walter Houser Brattain": [1956],
  "William Shockley": [1956],
  "Tsung-Dao Lee": [1957],
  "Chen-Ning Yang": [1957],
  "Pavel Alekseyevich Cherenkov": [1958],
  "Il'ja Mikhailovich Frank": [1958],
  "Igor Yevgenyevich Tamm": [1958],
  "Emilio Gino Segrè": [1959],
  "Owen Chamberlain": [1959],
  "Donald Arthur Glaser": [1960],
  "Robert Hofstadter": [1961],
  "Rudolf Ludwig Mössbauer": [1961],
  "Lev Davidovich Landau": [1962],
  "Eugene Paul Wigner": [1963],
  "Maria Goeppert-Mayer": [1963],
  "J. Hans D. Jensen": [1963],
  "Charles Hard Townes": [1964],
  "Nikolay Gennadiyevich Basov": [1964],
  "Aleksandr Mikhailovich Prokhorov": [1964],
  "Sin-Itiro Tomonaga": [1965],
  "Julian Schwinger": [1965],
  "Richard P. Feynman": [1965],
  "Richard Feynman": [1965],
  "Alfred Kastler": [1966],
  "Hans Albrecht Bethe": [1967],
  "Luis Walter Alvarez": [1968],
  "Murray Gell-Mann": [1969],
  "Hannes Alfvén": [1970],
  "Louis Néel": [1970],
  "Dennis Gabor": [1971],
  "Leon Neil Cooper": [1972],
  "John Robert Schrieffer": [1972],
  "Leo Esaki": [1973],
  "Ivar Giaever": [1973],
  "Brian David Josephson": [1973],
  "Martin Ryle": [1974],
  "Antony Hewish": [1974],
  "Aage Niels Bohr": [1975],
  "Ben Roy Mottelson": [1975],
  "Leo James Rainwater": [1975],
  "Burton Richter": [1976],
  "Samuel Chao Chung Ting": [1976],
  "Philip Warren Anderson": [1977],
  "Nevill Francis Mott": [1977],
  "John Hasbrouck Van Vleck": [1977],
  "Pyotr Leonidovich Kapitsa": [1978],
  "Arno Allan Penzias": [1978],
  "Robert Woodrow Wilson": [1978],
  "Sheldon Lee Glashow": [1979],
  "Sheldon Glashow": [1979],
  "Abdus Salam": [1979],
  "Steven Weinberg": [1979],
  "James Watson Cronin": [1980],
  "Val Logsdon Fitch": [1980],
  "Nicolaas Bloembergen": [1981],
  "Arthur Leonard Schawlow": [1981],
  "Kai Manne Börje Siegbahn": [1981],
  "Kenneth G. Wilson": [1982],
  "Subrahmanyan Chandrasekhar": [1983],
  "William Alfred Fowler": [1983],
  "Carlo Rubbia": [1984],
  "Simon van der Meer": [1984],
  "Klaus von Klitzing": [1985],
  "Ernst Ruska": [1986],
  "Gerd Binnig": [1986],
  "Heinrich Rohrer": [1986],
  "J. Georg Bednorz": [1987],
  "K. Alexander Müller": [1987],
  "Leon M. Lederman": [1988],
  "Melvin Schwartz": [1988],
  "Jack Steinberger": [1988],
  "Norman F. Ramsey": [1989],
  "Hans G. Dehmelt": [1989],
  "Wolfgang Paul": [1989],
  "Jerome I. Friedman": [1990],
  "Henry W. Kendall": [1990],
  "Richard E. Taylor": [1990],
  "Pierre-Gilles de Gennes": [1991],
  "Georges Charpak": [1992],
  "Russell A. Hulse": [1993],
  "Joseph H. Taylor Jr.": [1993],
  "Bertram N. Brockhouse": [1994],
  "Clifford G. Shull": [1994],
  "Martin L. Perl": [1995],
  "Frederick Reines": [1995],
  "David M. Lee": [1996],
  "Douglas D. Osheroff": [1996],
  "Robert C. Richardson": [1996],
  "Steven Chu": [1997],
  "Claude Cohen-Tannoudji": [1997],
  "William D. Phillips": [1997],
  "Robert B. Laughlin": [1998],
  "Horst L. Störmer": [1998],
  "Daniel C. Tsui": [1998],
  "Gerardus 't Hooft": [1999],
  "Martinus J. G. Veltman": [1999],
  "Zhores I. Alferov": [2000],
  "Herbert Kroemer": [2000],
  "Jack S. Kilby": [2000],
  "Eric A. Cornell": [2001],
  "Wolfgang Ketterle": [2001],
  "Carl E. Wieman": [2001],
  "Raymond Davis Jr.": [2002],
  "Masatoshi Koshiba": [2002],
  "Riccardo Giacconi": [2002],
  "Alexei A. Abrikosov": [2003],
  "Vitaly L. Ginzburg": [2003],
  "Anthony J. Leggett": [2003],
  "David J. Gross": [2004],
  "H. David Politzer": [2004],
  "Frank Wilczek": [2004],
  "Roy J. Glauber": [2005],
  "John L. Hall": [2005],
  "Theodor W. Hänsch": [2005],
  "John C. Mather": [2006],
  "George F. Smoot": [2006],
  "Albert Fert": [2007],
  "Peter Grünberg": [2007],
  "Makoto Kobayashi": [2008],
  "Toshihide Maskawa": [2008],
  "Yoichiro Nambu": [2008],
  "Charles K. Kao": [2009],
  "Willard S. Boyle": [2009],
  "George E. Smith": [2009],
  "Andre Geim": [2010],
  "Konstantin Novoselov": [2010],
  "Saul Perlmutter": [2011],
  "Brian P. Schmidt": [2011],
  "Adam G. Riess": [2011],
  "Serge Haroche": [2012],
  "David J. Wineland": [2012],
  "François Englert": [2013],
  "Peter W. Higgs": [2013],
  "Peter Higgs": [2013],
  "Isamu Akasaki": [2014],
  "Hiroshi Amano": [2014],
  "Shuji Nakamura": [2014],
  "Takaaki Kajita": [2015],
  "Arthur B. McDonald": [2015],
  "David J. Thouless": [2016],
  "F. Duncan M. Haldane": [2016],
  "J. Michael Kosterlitz": [2016],
  "Rainer Weiss": [2017],
  "Barry C. Barish": [2017],
  "Kip S. Thorne": [2017],
  "Arthur Ashkin": [2018],
  "Gérard Mourou": [2018],
  "Donna Strickland": [2018],
  "James Peebles": [2019],
  "Michel Mayor": [2019],
  "Didier Queloz": [2019],
  "Roger Penrose": [2020],
  "Reinhard Genzel": [2020],
  "Andrea Ghez": [2020],
  "Syukuro Manabe": [2021],
  "Klaus Hasselmann": [2021],
  "Giorgio Parisi": [2021],
  "Alain Aspect": [2022],
  "John F. Clauser": [2022],
  "Anton Zeilinger": [2022],
  "Pierre Agostini": [2023],
  "Ferenc Krausz": [2023],
  "Anne L'Huillier": [2023]
};

// Kyoto Prize in Basic Sciences awards by year (most relevant for physics)
const kyotoPrizes = {
  1985: "Claude Elwood Shannon - For outstanding contributions to the establishment of information theory",
  1986: "Rudolf Mössbauer - For outstanding contributions to the discovery of the Mössbauer effect and its applications",
  1987: "No prize awarded in Basic Sciences",
  1988: "John Archibald Wheeler - For outstanding contributions to theoretical physics, especially in general relativity and quantum mechanics",
  1989: "Roger Wolcott Sperry - For outstanding contributions to the understanding of brain functions",
  1990: "George Evelyn Hutchinson - For outstanding contributions to ecology",
  1991: "André Weil - For outstanding contributions to mathematics",
  1992: "David Turnbull - For outstanding contributions to materials science",
  1993: "Motoo Kimura - For outstanding contributions to evolutionary biology",
  1994: "Francis Harry Compton Crick - For outstanding contributions to molecular biology",
  1995: "Vladimir Igorevich Arnold - For outstanding contributions to mathematics",
  1996: "Shigefumi Mori - For outstanding contributions to algebraic geometry",
  1997: "Daniel Janzen - For outstanding contributions to ecology",
  1998: "Andrei Linde - For outstanding contributions to cosmology and inflationary universe theory",
  1999: "George Whitesides - For outstanding contributions to chemistry and materials science",
  2000: "No prize awarded in Basic Sciences",
  2001: "John Maynard Smith - For outstanding contributions to evolutionary biology",
  2002: "Mikhail Leonidovich Gromov - For outstanding contributions to mathematics",
  2003: "Eugene Parker - For outstanding contributions to solar physics and space science",
  2004: "Alfred G. Knudson - For outstanding contributions to cancer genetics",
  2005: "Simon A. Levin - For outstanding contributions to ecology",
  2006: "Shinya Yamanaka - For outstanding contributions to stem cell research",
  2007: "Robert H. May - For outstanding contributions to ecology and population biology",
  2008: "Rashid Sunyaev - For outstanding contributions to cosmology and astrophysics",
  2009: "Peter Raymond Grant and Barbara Rosemary Grant - For outstanding contributions to evolutionary biology",
  2010: "Leroy Hood - For outstanding contributions to systems biology",
  2011: "Rashid Sunyaev - For outstanding contributions to cosmology and astrophysics",
  2012: "Masatoshi Nei - For outstanding contributions to evolutionary biology",
  2013: "David Tilman - For outstanding contributions to ecology",
  2014: "Edward Witten - For outstanding contributions to theoretical physics and mathematics",
  2015: "Michel Mayor - For outstanding contributions to astronomy and exoplanet research",
  2016: "Hiroshi Matsumoto - For outstanding contributions to space science",
  2017: "Graham Farquhar - For outstanding contributions to plant physiology",
  2018: "Masaki Kashiwara - For outstanding contributions to mathematics",
  2019: "Charles David Allis - For outstanding contributions to epigenetics",
  2020: "No prize awarded in Basic Sciences",
  2021: "Rashid Sunyaev - For outstanding contributions to cosmology and astrophysics",
  2022: "Jeffrey I. Gordon - For outstanding contributions to microbiome research",
  2023: "No prize awarded in Basic Sciences",
  2024: "No prize awarded in Basic Sciences"
};

// Kyoto Prize years for people (array of years they won in Basic Sciences)
const peopleKyoto = {
  "Claude Elwood Shannon": [1985],
  "Claude Shannon": [1985],
  "Rudolf Mössbauer": [1986],
  "Rudolf Ludwig Mössbauer": [1986],
  "John Archibald Wheeler": [1988],
  "Andrei Linde": [1998],
  "Eugene Parker": [2003],
  "Rashid Sunyaev": [2008, 2011, 2021],
  "Edward Witten": [2014],
  "Michel Mayor": [2015]
};

// Nobel Prize in Chemistry years for people (selected physics-relevant)
const peopleNobelChemistry = {
  "Marie Curie": [1911],
  "Ernest Rutherford": [1908],
  "Linus Carl Pauling": [1954],
  "Linus Pauling": [1954],
  "Lars Onsager": [1968],
  "Gerhard Herzberg": [1971],
  "Ilya Prigogine": [1977],
  "Walter Kohn": [1998],
  "John A. Pople": [1998]
};

// Nobel Prize in Medicine/Physiology years for people (selected physics-relevant)
const peopleNobelMedicine = {
  "Francis Harry Compton Crick": [1962],
  "Francis Crick": [1962],
  "James Dewey Watson": [1962],
  "James Watson": [1962],
  "Maurice Hugh Frederick Wilkins": [1962],
  "Maurice Wilkins": [1962]
};

// Nobel Prize in Economic Sciences years for people (selected physics-relevant)
const peopleNobelEconomics = {
  "Leonid Vitaliyevich Kantorovich": [1975],
  "Leonid Kantorovich": [1975]
};

// Nobel Prize in Chemistry awards by year
const nobelPrizesChemistry = {
  1901: "Jacobus Henricus van 't Hoff - Laws of chemical dynamics and osmotic pressure in solutions",
  1902: "Hermann Emil Fischer - Work on sugar and purine syntheses",
  1903: "Svante August Arrhenius - Theory of electrolytic dissociation",
  1904: "Sir William Ramsay - Discovery of the inert gaseous elements in air",
  1905: "Johann Friedrich Wilhelm Adolf von Baeyer - Work on organic dyes and hydroaromatic compounds",
  1906: "Henri Moissan - Investigation and isolation of the element fluorine",
  1907: "Eduard Buchner - Biochemical researches and discovery of cell-free fermentation",
  1908: "Ernest Rutherford - Investigations into the disintegration of the elements, and the chemistry of radioactive substances",
  1909: "Wilhelm Ostwald - Work on catalysis and investigations into the fundamental principles governing chemical equilibria and rates of reaction",
  1910: "Otto Wallach - Work in the field of alicyclic compounds",
  1911: "Marie Curie - Discovery of the elements radium and polonium",
  1912: "Victor Grignard and Paul Sabatier - Development of methods of organic synthesis",
  1913: "Alfred Werner - Work on the linkage of atoms in molecules",
  1914: "Theodore William Richards - Determinations of the atomic weights of a large number of elements",
  1915: "Richard Martin Willstätter - Research on plant pigments, especially chlorophyll",
  1916: "No prize awarded",
  1917: "No prize awarded",
  1918: "Fritz Haber - Synthesis of ammonia from its elements",
  1919: "No prize awarded",
  1920: "Walther Nernst - Work in thermochemistry",
  1921: "Frederick Soddy - Contributions to knowledge of the chemistry of radioactive substances, and investigations into the origin and nature of isotopes",
  1922: "Francis William Aston - Discovery of isotopes in a large number of non-radioactive elements, and for his enunciation of the whole-number rule",
  1923: "Fritz Pregl - Invention of the method of micro-analysis of organic substances",
  1924: "No prize awarded",
  1925: "Richard Adolf Zsigmondy - Demonstration of the heterogeneous nature of colloid solutions",
  1926: "Theodor Svedberg - Work on disperse systems",
  1927: "Heinrich Otto Wieland - Investigations of the constitution of the bile acids and related substances",
  1928: "Adolf Otto Reinhold Windaus - Service in the investigation of the constitution of the sterols and their connection with the vitamins",
  1929: "Arthur Harden and Hans Karl August Simon von Euler-Chelpin - Investigations on the fermentation of sugar and fermentative enzymes",
  1930: "Hans Fischer - Work on the constitution of haemin and chlorophyll",
  1931: "Carl Bosch and Friedrich Bergius - Invention and development of chemical high pressure methods",
  1932: "Irving Langmuir - Discoveries and investigations in surface chemistry",
  1933: "No prize awarded",
  1934: "Harold Clayton Urey - Discovery of heavy hydrogen",
  1935: "Frédéric Joliot and Irène Joliot-Curie - Synthesis of new radioactive elements",
  1936: "Petrus (Peter) Josephus Wilhelmus Debye - Contributions to our knowledge of molecular structure through investigations on dipole moments and on the diffraction of X-rays and electrons in gases",
  1937: "Walter Norman Haworth and Paul Karrer - Investigations on carbohydrates and vitamin C; Investigations on carotenoids, flavins and vitamins A and B2",
  1938: "Richard Kuhn - Work on carotenoids and vitamins",
  1939: "Adolf Friedrich Johann Butenandt and Leopold Ruzicka - Work on sex hormones; Work on polymethylenes and higher terpenes",
  1940: "No prize awarded",
  1941: "No prize awarded",
  1942: "No prize awarded",
  1943: "George de Hevesy - Work on the use of isotopes as tracers in the study of chemical processes",
  1944: "Otto Hahn - Discovery of the fission of heavy nuclei",
  1945: "Artturi Ilmari Virtanen - Research and inventions in agricultural and nutrition chemistry",
  1946: "James Batcheller Sumner, John Howard Northrop, and Wendell Meredith Stanley - Discovery that enzymes can be crystallized; Preparation of enzymes and virus proteins in a pure form",
  1947: "Sir Robert Robinson - Investigations on plant products of biological importance, especially the alkaloids",
  1948: "Arne Wilhelm Kaurin Tiselius - Research on electrophoresis and adsorption analysis, especially for discoveries concerning the complex nature of the serum proteins",
  1949: "William Francis Giauque - Contributions in the field of chemical thermodynamics, particularly concerning the behaviour of substances at extremely low temperatures",
  1950: "Otto Paul Hermann Diels and Kurt Alder - Discovery and development of the diene synthesis",
  1951: "Edwin Mattison McMillan and Glenn Theodore Seaborg - Discoveries in the chemistry of the transuranium elements",
  1952: "Archer John Porter Martin and Richard Laurence Millington Synge - Invention of partition chromatography",
  1953: "Hermann Staudinger - Discoveries in the field of macromolecular chemistry",
  1954: "Linus Carl Pauling - Research into the nature of the chemical bond",
  1955: "Vincent du Vigneaud - Work on biochemically important sulphur compounds",
  1956: "Sir Cyril Norman Hinshelwood and Nikolay Nikolaevich Semenov - Researches into the mechanism of chemical reactions",
  1957: "Sir Alexander R. Todd - Work on nucleotides and nucleotide co-enzymes",
  1958: "Frederick Sanger - Work on the structure of proteins, especially that of insulin",
  1959: "Jaroslav Heyrovský - Discovery and development of the polarographic methods of analysis",
  1960: "Willard Frank Libby - Method to use carbon-14 for age determination in archaeology, geology, geophysics, and other branches of science",
  1961: "Melvin Calvin - Research on the carbon dioxide assimilation in plants",
  1962: "Max Ferdinand Perutz and John Cowdery Kendrew - Studies of the structures of globular proteins",
  1963: "Karl Ziegler and Giulio Natta - Discoveries in the field of the chemistry and technology of high polymers",
  1964: "Dorothy Crowfoot Hodgkin - Determinations by X-ray techniques of the structures of important biochemical substances",
  1965: "Robert Burns Woodward - Achievements in the art of organic synthesis",
  1966: "Robert Sanderson Mulliken - Fundamental work concerning chemical bonds and the electronic structure of molecules",
  1967: "Manfred Eigen, Ronald George Wreyford Norrish, and George Porter - Studies of extremely fast chemical reactions",
  1968: "Lars Onsager - Discovery of the reciprocal relations bearing his name, which are fundamental for the thermodynamics of irreversible processes",
  1969: "Derek H. R. Barton and Odd Hassel - Development of the concept of conformation and its application in chemistry",
  1970: "Luis F. Leloir - Discovery of sugar nucleotides and their role in the biosynthesis of carbohydrates",
  1971: "Gerhard Herzberg - Contributions to the knowledge of electronic structure and geometry of molecules, particularly free radicals",
  1972: "Christian B. Anfinsen, Stanford Moore, and William H. Stein - Work on ribonuclease, especially concerning the connection between the amino acid sequence and the biologically active conformation",
  1973: "Ernst Otto Fischer and Geoffrey Wilkinson - Pioneering work on the chemistry of the organometallic compounds",
  1974: "Paul J. Flory - Fundamental achievements, both theoretical and experimental, in the physical chemistry of the macromolecules",
  1975: "John Warcup Cornforth and Vladimir Prelog - Work on the stereochemistry of enzyme-catalyzed reactions; Research into the stereochemistry of organic molecules and reactions",
  1976: "William N. Lipscomb - Studies on the structure of boranes illuminating problems of chemical bonding",
  1977: "Ilya Prigogine - Contributions to non-equilibrium thermodynamics, particularly the theory of dissipative structures",
  1978: "Peter D. Mitchell - Contribution to the understanding of biological energy transfer through the formulation of the chemiosmotic theory",
  1979: "Herbert C. Brown and Georg Wittig - Development of the use of boron- and phosphorus-containing compounds, respectively, into important reagents in organic synthesis",
  1980: "Paul Berg, Walter Gilbert, and Frederick Sanger - Fundamental studies of the biochemistry of nucleic acids, with particular regard to recombinant-DNA; Determination of base sequences in nucleic acids",
  1981: "Kenichi Fukui and Roald Hoffmann - Theories, developed independently, concerning the course of chemical reactions",
  1982: "Aaron Klug - Development of crystallographic electron microscopy and his structural elucidation of biologically important nucleic acid-protein complexes",
  1983: "Henry Taube - Work on the mechanisms of electron transfer reactions, especially in metal complexes",
  1984: "Robert Bruce Merrifield - Development of methodology for chemical synthesis on a solid matrix",
  1985: "Herbert A. Hauptman and Jerome Karle - Outstanding achievements in the development of direct methods for the determination of crystal structures",
  1986: "Dudley R. Herschbach, Yuan T. Lee, and John C. Polanyi - Contributions concerning the dynamics of chemical elementary processes",
  1987: "Donald J. Cram, Jean-Marie Lehn, and Charles J. Pedersen - Development and use of molecules with structure-specific interactions of high selectivity",
  1988: "Johann Deisenhofer, Robert Huber, and Hartmut Michel - Determination of the three-dimensional structure of a photosynthetic reaction centre",
  1989: "Sidney Altman and Thomas R. Cech - Discovery of catalytic properties of RNA",
  1990: "Elias James Corey - Development of the theory and methodology of organic synthesis",
  1991: "Richard R. Ernst - Contributions to the development of the methodology of high resolution nuclear magnetic resonance (NMR) spectroscopy",
  1992: "Rudolph A. Marcus - Contributions to the theory of electron transfer reactions in chemical systems",
  1993: "Kary B. Mullis and Michael Smith - Invention of the polymerase chain reaction (PCR) method; Fundamental contributions to the establishment of oligonucleotide-based, site-directed mutagenesis",
  1994: "George A. Olah - Contribution to carbocation chemistry",
  1995: "Paul J. Crutzen, Mario J. Molina, and F. Sherwood Rowland - Work in atmospheric chemistry, particularly concerning the formation and decomposition of ozone",
  1996: "Robert F. Curl Jr., Sir Harold W. Kroto, and Richard E. Smalley - Discovery of fullerenes",
  1997: "Paul D. Boyer and John E. Walker - Elucidation of the enzymatic mechanism underlying the synthesis of adenosine triphosphate (ATP); Discovery of the enzymatic mechanism underlying the synthesis of adenosine triphosphate (ATP)",
  1997: "Jens C. Skou - First discovery of an ion-transporting enzyme, Na+, K+ -ATPase",
  1998: "Walter Kohn - Development of the density-functional theory; John A. Pople - Development of computational methods in quantum chemistry",
  1999: "Ahmed H. Zewail - Studies of the transition states of chemical reactions using femtosecond spectroscopy",
  2000: "Alan J. Heeger, Alan G. MacDiarmid, and Hideki Shirakawa - Discovery and development of conductive polymers",
  2001: "William S. Knowles and Ryoji Noyori - Work on chirally catalysed hydrogenation reactions; K. Barry Sharpless - Work on chirally catalysed oxidation reactions",
  2002: "John B. Fenn and Koichi Tanaka - Development of methods for identification and structure analyses of biological macromolecules; Development of soft desorption ionisation methods for mass spectrometric analyses of biological macromolecules",
  2002: "Kurt Wüthrich - Development of nuclear magnetic resonance spectroscopy for determining the three-dimensional structure of biological macromolecules in solution",
  2003: "Peter Agre and Roderick MacKinnon - Discoveries concerning channels in cell membranes; Structural and mechanistic studies of ion channels",
  2004: "Aaron Ciechanover, Avram Hershko, and Irwin Rose - Discovery of ubiquitin-mediated protein degradation",
  2005: "Robert H. Grubbs, Richard R. Schrock, and Yves Chauvin - Development of the metathesis method in organic synthesis",
  2006: "Roger D. Kornberg - Studies of the molecular basis of eukaryotic transcription",
  2007: "Gerhard Ertl - Studies of chemical processes on solid surfaces",
  2008: "Osamu Shimomura, Martin Chalfie, and Roger Y. Tsien - Discovery and development of the green fluorescent protein, GFP",
  2009: "Venkatraman Ramakrishnan, Thomas A. Steitz, and Ada E. Yonath - Studies of the structure and function of the ribosome",
  2010: "Richard F. Heck, Ei-ichi Negishi, and Akira Suzuki - Palladium-catalyzed cross couplings in organic synthesis",
  2011: "Dan Shechtman - Discovery of quasicrystals",
  2012: "Robert J. Lefkowitz and Brian K. Kobilka - Studies of G-protein-coupled receptors",
  2013: "Martin Karplus, Michael Levitt, and Arieh Warshel - Development of multiscale models for complex chemical systems",
  2014: "Eric Betzig, Stefan W. Hell, and William E. Moerner - Development of super-resolved fluorescence microscopy",
  2015: "Tomas Lindahl, Paul Modrich, and Aziz Sancar - Mechanistic studies of DNA repair",
  2016: "Jean-Pierre Sauvage, Sir J. Fraser Stoddart, and Bernard L. Feringa - Design and synthesis of molecular machines",
  2017: "Jacques Dubochet, Joachim Frank, and Richard Henderson - Development of cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution",
  2018: "Frances H. Arnold - Directed evolution of enzymes; George P. Smith and Sir Gregory P. Winter - Phage display of peptides and antibodies",
  2019: "John B. Goodenough, M. Stanley Whittingham, and Akira Yoshino - Development of lithium-ion batteries",
  2020: "Emmanuelle Charpentier and Jennifer A. Doudna - Development of a method for genome editing",
  2021: "Benjamin List and David W.C. MacMillan - Development of asymmetric organocatalysis",
  2022: "Carolyn R. Bertozzi, Morten Meldal, and K. Barry Sharpless - Development of click chemistry and bioorthogonal chemistry",
  2023: "Moungi G. Bawendi, Louis E. Brus, and Alexei I. Ekimov - Discovery and synthesis of quantum dots",
  2024: "No prize awarded yet"
};

// Nobel Prize in Physiology or Medicine awards by year (selected relevant ones)
const nobelPrizesMedicine = {
  1901: "Emil Adolf von Behring - Work on serum therapy",
  1902: "Ronald Ross - Work on malaria",
  1903: "Niels Ryberg Finsen - Treatment of diseases, especially lupus vulgaris, with concentrated light radiation",
  1904: "Ivan Petrovich Pavlov - Work on the physiology of digestion",
  1905: "Robert Koch - Investigations and discoveries in relation to tuberculosis",
  1906: "Camillo Golgi and Santiago Ramón y Cajal - Work on the structure of the nervous system",
  1907: "Charles Louis Alphonse Laveran - Work on the role played by protozoa in causing diseases",
  1908: "Ilya Ilyich Mechnikov and Paul Ehrlich - Work on immunity",
  1909: "Emil Theodor Kocher - Work on the physiology, pathology and surgery of the thyroid gland",
  1910: "Albrecht Kossel - Contributions to our knowledge of cell chemistry",
  1911: "Allvar Gullstrand - Work on the dioptrics of the eye",
  1912: "Alexis Carrel - Work on vascular suture and the transplantation of blood vessels and organs",
  1913: "Charles Richet - Work on anaphylaxis",
  1914: "Robert Bárány - Work on the physiology and pathology of the vestibular apparatus",
  1915: "No prize awarded",
  1916: "No prize awarded",
  1917: "No prize awarded",
  1918: "No prize awarded",
  1919: "Jules Bordet - Discoveries relating to immunity",
  1920: "Schack August Steenberg Krogh - Discovery of the capillary motor regulating mechanism",
  1921: "No prize awarded",
  1922: "Archibald Vivian Hill - Discovery relating to the production of heat in the muscle; Otto Fritz Meyerhof - Discovery of the fixed relationship between the consumption of oxygen and the metabolism of lactic acid in the muscle",
  1923: "Frederick Grant Banting and John James Rickard Macleod - Discovery of insulin",
  1924: "Willem Einthoven - Discovery of the mechanism of the electrocardiogram",
  1925: "No prize awarded",
  1926: "Johannes Andreas Grib Fibiger - Discovery of the Spiroptera carcinoma",
  1927: "Julius Wagner-Jauregg - Discovery of the therapeutic value of malaria inoculation in the treatment of dementia paralytica",
  1928: "Charles Jules Henri Nicolle - Work on typhus",
  1929: "Christiaan Eijkman - Discovery of the antineuritic vitamin; Sir Frederick Gowland Hopkins - Discovery of the growth-stimulating vitamins",
  1930: "Karl Landsteiner - Discovery of human blood groups",
  1931: "Otto Heinrich Warburg - Discovery of the nature and mode of action of the respiratory enzyme",
  1932: "Sir Charles Scott Sherrington and Edgar Douglas Adrian - Discoveries regarding the functions of neurons",
  1933: "Thomas Hunt Morgan - Discoveries concerning the role played by the chromosome in heredity",
  1934: "George Hoyt Whipple, George Richards Minot, and William Parry Murphy - Discoveries concerning liver therapy in cases of anaemia",
  1935: "Hans Spemann - Discovery of the organizer effect in embryonic development",
  1936: "Sir Henry Hallett Dale and Otto Loewi - Discoveries relating to chemical transmission of nerve impulses",
  1937: "Albert von Szent-Györgyi Nagyrapolt - Discoveries in connection with the biological combustion processes, with special reference to vitamin C and the catalysis of fumaric acid",
  1938: "Cornell Heymans - Discovery of the role played by the sinus and aortic mechanisms in the regulation of respiration",
  1939: "Gerhard Domagk - Discovery of the antibacterial effects of prontosil",
  1940: "No prize awarded",
  1941: "No prize awarded",
  1942: "No prize awarded",
  1943: "Henrik Carl Peter Dam - Discovery of vitamin K; Edward Adelbert Doisy - Discovery of the chemical nature of vitamin K",
  1944: "Joseph Erlanger and Herbert Spencer Gasser - Discoveries relating to the highly differentiated functions of single nerve fibres",
  1945: "Sir Alexander Fleming, Ernst Boris Chain, and Sir Howard Walter Florey - Discovery of penicillin and its curative effect in various infectious diseases",
  1946: "Hermann Joseph Muller - Discovery of the production of mutations by means of X-ray irradiation",
  1947: "Carl Ferdinand Cori and Gerty Theresa Cori - Discovery of the course of the catalytic conversion of glycogen; Bernardo Alberto Houssay - Discovery of the part played by the hormone of the anterior pituitary lobe in the metabolism of sugar",
  1948: "Paul Hermann Müller - Discovery of the high efficiency of DDT as a contact poison against several arthropods",
  1949: "Walter Rudolf Hess - Discovery of the functional organization of the interbrain as a coordinator of the activities of the internal organs; António Caetano de Abreu Freire Egas Moniz - Discovery of the therapeutic value of leucotomy in certain psychoses",
  1950: "Edward Calvin Kendall, Tadeus Reichstein, and Philip Showalter Hench - Discoveries relating to the hormones of the adrenal cortex, their structure and biological effects",
  1951: "Max Theiler - Discoveries concerning yellow fever and how to combat it",
  1952: "Selman Abraham Waksman - Discovery of streptomycin, the first antibiotic effective against tuberculosis",
  1953: "Hans Adolf Krebs - Discovery of the citric acid cycle; Fritz Albert Lipmann - Discovery of co-enzyme A and its importance for intermediary metabolism",
  1954: "John Franklin Enders, Thomas Huckle Weller, and Frederick Chapman Robbins - Discovery of the ability of poliomyelitis viruses to grow in cultures of various types of tissue",
  1955: "Hugo Theorell - Discoveries concerning the nature and mode of action of oxidation enzymes",
  1956: "André Frédéric Cournand, Werner Forssmann, and Dickinson W. Richards - Discoveries concerning heart catheterization and pathological changes in the circulatory system",
  1957: "Daniel Bovet - Discoveries relating to synthetic compounds that inhibit the action of certain body substances",
  1958: "George Wells Beadle and Edward Lawrie Tatum - Discovery that genes act by regulating definite chemical events; Joshua Lederberg - Discoveries concerning genetic recombination and the organization of the genetic material of bacteria",
  1959: "Severo Ochoa and Arthur Kornberg - Discovery of the mechanisms in the biological synthesis of ribonucleic acid and deoxyribonucleic acid",
  1960: "Sir Frank Macfarlane Burnet and Peter Brian Medawar - Discovery of acquired immunological tolerance",
  1961: "Georg von Békésy - Discoveries of the physical mechanism of stimulation within the cochlea",
  1962: "Francis Harry Compton Crick, James Dewey Watson, and Maurice Hugh Frederick Wilkins - Discoveries concerning the molecular structure of nucleic acids and its significance for information transfer in living material",
  1963: "Sir John Carew Eccles, Alan Lloyd Hodgkin, and Andrew Fielding Huxley - Discoveries concerning the ionic mechanisms involved in excitation and inhibition in the peripheral and central portions of the nerve cell membrane",
  1964: "Konrad Bloch and Feodor Lynen - Discoveries concerning the mechanism and regulation of the cholesterol and fatty acid metabolism",
  1965: "François Jacob, André Lwoff, and Jacques Monod - Discoveries concerning genetic control of enzyme and virus synthesis",
  1966: "Peyton Rous - Discovery of tumour-inducing viruses; Charles Brenton Huggins - Discoveries concerning hormonal treatment of prostatic cancer",
  1967: "Ragnar Granit, Haldan Keffer Hartline, and George Wald - Discoveries concerning the primary physiological and chemical visual processes in the eye",
  1968: "Robert W. Holley, Har Gobind Khorana, and Marshall W. Nirenberg - Interpretation of the genetic code and its function in protein synthesis",
  1969: "Max Delbrück, Alfred D. Hershey, and Salvador E. Luria - Discoveries concerning the replication mechanism and the genetic structure of viruses",
  1970: "Sir Bernard Katz, Ulf von Euler, and Julius Axelrod - Discoveries concerning the humoral transmittors in the nerve terminals and the mechanism for their storage, release and inactivation",
  1971: "Earl W. Sutherland, Jr. - Discoveries concerning the mechanisms of the action of hormones",
  1972: "Gerald M. Edelman and Rodney R. Porter - Discoveries concerning the chemical structure of antibodies",
  1973: "Karl von Frisch, Konrad Lorenz, and Nikolaas Tinbergen - Discoveries concerning organization and elicitation of individual and social behaviour patterns",
  1974: "Albert Claude, Christian de Duve, and George E. Palade - Discoveries concerning the structural and functional organization of the cell",
  1975: "David Baltimore, Renato Dulbecco, and Howard Martin Temin - Discoveries concerning the interaction between tumour viruses and the genetic material of the cell",
  1976: "Baruch S. Blumberg and D. Carleton Gajdusek - Discoveries concerning new mechanisms for the origin and dissemination of infectious diseases",
  1977: "Roger Guillemin, Andrew V. Schally, and Rosalyn Yalow - Discoveries concerning the peptide hormone production of the brain; Development of radioimmunoassays of peptide hormones",
  1978: "Werner Arber, Daniel Nathans, and Hamilton O. Smith - Discovery of restriction enzymes and their application to problems of molecular genetics",
  1979: "Allan M. Cormack and Godfrey N. Hounsfield - Development of computer assisted tomography",
  1980: "Baruj Benacerraf, Jean Dausset, and George D. Snell - Discoveries concerning genetically determined structures on the cell surface that regulate immunological reactions",
  1981: "Roger W. Sperry - Discoveries concerning the functional specialization of the cerebral hemispheres; David H. Hubel and Torsten N. Wiesel - Discoveries concerning information processing in the visual system",
  1982: "Sune K. Bergström, Bengt I. Samuelsson, and John R. Vane - Discoveries concerning prostaglandins and related biologically active substances",
  1983: "Barbara McClintock - Discovery of mobile genetic elements",
  1984: "Niels K. Jerne, Georges J.F. Köhler, and César Milstein - Theories concerning the specificity in development and control of the immune system and the discovery of the principle for production of monoclonal antibodies",
  1985: "Michael S. Brown and Joseph L. Goldstein - Discoveries concerning the regulation of cholesterol metabolism",
  1986: "Stanley Cohen and Rita Levi-Montalcini - Discoveries of growth factors",
  1987: "Susumu Tonegawa - Discovery of the genetic principle for generation of antibody diversity",
  1988: "Sir James W. Black, Gertrude B. Elion, and George H. Hitchings - Discoveries of important principles for drug treatment",
  1989: "J. Michael Bishop and Harold E. Varmus - Discovery of the cellular origin of retroviral oncogenes",
  1990: "Joseph E. Murray and E. Donnall Thomas - Discoveries concerning organ and cell transplantation in the treatment of human disease",
  1991: "Erwin Neher and Bert Sakmann - Discoveries concerning the function of single ion channels in cells",
  1992: "Edmond H. Fischer and Edwin G. Krebs - Discoveries concerning reversible protein phosphorylation as a biological regulatory mechanism",
  1993: "Richard J. Roberts and Phillip A. Sharp - Discoveries of split genes",
  1994: "Alfred G. Gilman and Martin Rodbell - Discovery of G-proteins and the role of these proteins in signal transduction in cells",
  1995: "Edward B. Lewis, Christiane Nüsslein-Volhard, and Eric F. Wieschaus - Discoveries concerning the genetic control of early embryonic development",
  1996: "Peter C. Doherty and Rolf M. Zinkernagel - Discoveries concerning the specificity of the cell mediated immune defence",
  1997: "Stanley B. Prusiner - Discovery of Prions - a new biological principle of infection",
  1998: "Robert F. Furchgott, Louis J. Ignarro, and Ferid Murad - Discoveries concerning nitric oxide as a signalling molecule in the cardiovascular system",
  1999: "Günter Blobel - Discovery that proteins have intrinsic signals that govern their transport and localization in the cell",
  2000: "Arvid Carlsson, Paul Greengard, and Eric R. Kandel - Discoveries concerning signal transduction in the nervous system",
  2001: "Leland H. Hartwell, Tim Hunt, and Sir Paul M. Nurse - Discoveries of key regulators of the cell cycle",
  2002: "Sydney Brenner, H. Robert Horvitz, and John E. Sulston - Discoveries concerning genetic regulation of organ development and programmed cell death",
  2003: "Paul C. Lauterbur and Sir Peter Mansfield - Discoveries concerning magnetic resonance imaging",
  2004: "Richard Axel and Linda B. Buck - Discoveries of odorant receptors and the organization of the olfactory system",
  2005: "Barry J. Marshall and J. Robin Warren - Discovery of the bacterium Helicobacter pylori and its role in gastritis and peptic ulcer disease",
  2006: "Andrew Z. Fire and Craig C. Mello - Discovery of RNA interference - gene silencing by double-stranded RNA",
  2007: "Mario R. Capecchi, Sir Martin J. Evans, and Oliver Smithies - Discoveries of principles for introducing specific gene modifications in mice by the use of embryonic stem cells",
  2008: "Harald zur Hausen - Discovery of human papilloma viruses causing cervical cancer; Françoise Barré-Sinoussi and Luc Montagnier - Discovery of human immunodeficiency virus",
  2009: "Elizabeth H. Blackburn, Carol W. Greider, and Jack W. Szostak - Discovery of how chromosomes are protected by telomeres and the enzyme telomerase",
  2010: "Robert G. Edwards - Development of in vitro fertilization",
  2011: "Bruce A. Beutler and Jules A. Hoffmann - Discoveries concerning the activation of innate immunity; Ralph M. Steinman - Discovery of the dendritic cell and its role in adaptive immunity",
  2012: "Sir John B. Gurdon and Shinya Yamanaka - Discovery that mature cells can be reprogrammed to become pluripotent",
  2013: "James E. Rothman, Randy W. Schekman, and Thomas C. Südhof - Discoveries of machinery regulating vesicle traffic, a major transport system in our cells",
  2014: "John O'Keefe, May-Britt Moser, and Edvard I. Moser - Discoveries of cells that constitute a positioning system in the brain",
  2015: "William C. Campbell and Satoshi Ōmura - Discoveries concerning a novel therapy against infections caused by roundworm parasites; Tu Youyou - Discoveries concerning a novel therapy against Malaria",
  2016: "Yoshinori Ohsumi - Discoveries of mechanisms for autophagy",
  2017: "Jeffrey C. Hall, Michael Rosbash, and Michael W. Young - Discoveries of molecular mechanisms controlling the circadian rhythm",
  2018: "James P. Allison and Tasuku Honjo - Discovery of cancer therapy by inhibition of negative immune regulation",
  2019: "William G. Kaelin Jr., Sir Peter J. Ratcliffe, and Gregg L. Semenza - Discoveries of how cells sense and adapt to oxygen availability",
  2020: "Harvey J. Alter, Michael Houghton, and Charles M. Rice - Discovery of Hepatitis C virus",
  2021: "David Julius and Ardem Patapoutian - Discoveries of receptors for temperature and touch",
  2022: "Svante Pääbo - Discoveries concerning the genomes of extinct hominins and human evolution",
  2023: "Katalin Karikó and Drew Weissman - Discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19",
  2024: "No prize awarded yet"
};

// Nobel Prize in Economic Sciences awards by year (selected relevant ones)
const nobelPrizesEconomics = {
  1969: "Ragnar Frisch and Jan Tinbergen - Development and application of dynamic models for the analysis of economic processes",
  1970: "Paul Samuelson - Scientific work through which he has developed static and dynamic economic theory",
  1971: "Simon Kuznets - Empirically founded interpretation of economic growth",
  1972: "John R. Hicks and Kenneth J. Arrow - Pioneering contributions to general economic equilibrium theory and welfare theory",
  1973: "Wassily Leontief - Development of the input-output method and for its application to important economic problems",
  1974: "Gunnar Myrdal and Friedrich August von Hayek - Pioneering work in the theory of money and economic fluctuations and for their penetrating analysis of the interdependence of economic, social and institutional phenomena",
  1975: "Leonid Vitaliyevich Kantorovich and Tjalling C. Koopmans - Contributions to the theory of optimum allocation of resources",
  1976: "Milton Friedman - Achievements in the fields of consumption analysis, monetary history and theory and for his demonstration of the complexity of stabilization policy",
  1977: "Bertil Ohlin and James E. Meade - Pathbreaking contribution to the theory of international trade and international capital movements",
  1978: "Herbert A. Simon - Pioneering research into the decision-making process within economic organizations",
  1979: "Theodore W. Schultz and Sir Arthur Lewis - Pioneering research into economic development research with particular consideration of the problems of developing countries",
  1980: "Lawrence R. Klein - Creation of econometric models and the application to the analysis of economic fluctuations and economic policies",
  1981: "James Tobin - Analysis of financial markets and their relations to expenditure decisions, employment, production and prices",
  1982: "George J. Stigler - Seminal studies of industrial structures, functioning of markets and causes and effects of public regulation",
  1983: "Gérard Debreu - Incorporation of new analytical methods into economic theory and his rigorous reformulation of the theory of general equilibrium",
  1984: "Richard Stone - Fundamental contributions to the development of systems of national accounts",
  1985: "Franco Modigliani - Pioneering analyses of saving and of financial markets",
  1986: "James M. Buchanan Jr. - Development of the contractual and constitutional bases for the theory of economic and political decision-making",
  1987: "Robert M. Solow - Contributions to the theory of economic growth",
  1988: "Maurice Allais - Pioneering contributions to the theory of markets and efficient utilization of resources",
  1989: "Trygve Haavelmo - Clarification of the probability theory foundations of econometrics and his analyses of simultaneous economic structures",
  1990: "Harry M. Markowitz, Merton H. Miller, and William F. Sharpe - Pioneering work in the theory of financial economics",
  1991: "Ronald H. Coase - Discovery and clarification of the significance of transaction costs and property rights for the institutional structure and functioning of the economy",
  1992: "Gary S. Becker - Extension of microeconomic analysis to a wide range of human behaviour and interaction, including nonmarket behaviour",
  1993: "Robert W. Fogel and Douglass C. North - Renewal of research in economic history by applying economic theory and quantitative methods in order to explain economic and institutional change",
  1994: "John C. Harsanyi, John F. Nash Jr., and Reinhard Selten - Pioneering analysis of equilibria in the theory of non-cooperative games",
  1995: "Robert E. Lucas Jr. - Development and application of the hypothesis of rational expectations and thereby having transformed macroeconomic analysis and deepened our understanding of economic policy",
  1996: "James A. Mirrlees and William Vickrey - Fundamental contributions to the economic theory of incentives under asymmetric information",
  1997: "Robert C. Merton and Myron S. Scholes - New method to determine the value of derivatives",
  1998: "Amartya Sen - Contributions to welfare economics",
  1999: "Robert A. Mundell - Analysis of monetary and fiscal policy under different exchange rate regimes and his analysis of optimum currency areas",
  2000: "James J. Heckman and Daniel L. McFadden - Development of theory and methods for analyzing selective samples; Development of theory and methods for analyzing discrete choice",
  2001: "George A. Akerlof, A. Michael Spence, and Joseph E. Stiglitz - Analyses of markets with asymmetric information",
  2002: "Daniel Kahneman - Integration of insights from psychological research into economic science, especially concerning human judgment and decision-making under uncertainty; Vernon L. Smith - Establishment of laboratory experiments as a tool in empirical economic analysis",
  2003: "Robert F. Engle III and Clive W.J. Granger - Methods of analyzing economic time series with time-varying volatility (ARCH); Methods of analyzing economic time series with common trends (cointegration)",
  2004: "Finn E. Kydland and Edward C. Prescott - Contributions to dynamic macroeconomics: the time consistency of economic policy and the driving forces behind business cycles",
  2005: "Robert J. Aumann and Thomas C. Schelling - Enhancement of our understanding of conflict and cooperation through game-theory analysis",
  2006: "Edmund S. Phelps - Analysis of intertemporal tradeoffs in macroeconomic policy",
  2007: "Leonid Hurwicz, Eric S. Maskin, and Roger B. Myerson - Having laid the foundations of mechanism design theory",
  2008: "Paul Krugman - Analysis of trade patterns and location of economic activity",
  2009: "Elinor Ostrom - Analysis of economic governance, especially the commons; Oliver E. Williamson - Analysis of economic governance, especially the boundaries of the firm",
  2010: "Peter A. Diamond, Dale T. Mortensen, and Christopher A. Pissarides - Analysis of markets with search frictions",
  2011: "Thomas J. Sargent and Christopher A. Sims - Empirical research on cause and effect in the macroeconomy",
  2012: "Alvin E. Roth and Lloyd S. Shapley - Theory of stable allocations and the practice of market design",
  2013: "Eugene F. Fama, Lars Peter Hansen, and Robert J. Shiller - Empirical analysis of asset prices",
  2014: "Jean Tirole - Analysis of market power and regulation",
  2015: "Angus Deaton - Analysis of consumption, poverty, and welfare",
  2016: "Oliver Hart and Bengt Holmström - Contributions to contract theory",
  2017: "Richard H. Thaler - Contributions to behavioural economics",
  2018: "William D. Nordhaus - Integrating climate change into long-run macroeconomic analysis; Paul M. Romer - Integrating technological innovations into long-run macroeconomic analysis",
  2019: "Abhijit Banerjee, Esther Duflo, and Michael Kremer - Experimental approach to alleviating global poverty",
  2020: "Paul R. Milgrom and Robert B. Wilson - Improvements to auction theory and inventions of new auction formats",
  2021: "David Card - Empirical contributions to labour economics; Joshua D. Angrist and Guido W. Imbens - Methodological contributions to the analysis of causal relationships",
  2022: "Ben S. Bernanke, Douglas W. Diamond, and Philip H. Dybvig - Research on banks and financial crises",
  2023: "Claudia Goldin - Having advanced our understanding of women's labour market outcomes",
  2024: "No prize awarded yet"
};
